global:
  scrape_interval: 15s

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: 'context-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['context-server:8000']

