global:
  scrape_interval: 15s

rule_files:
  - alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']


scrape_configs:
  - job_name: 'context-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['context-server:8000']

